# Generated by Django 4.1.6 on 2023-03-28 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyModel',
            fields=[
                ('agencyID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('agencyName', models.CharField(max_length=255)),
                ('agencyUrl', models.CharField(max_length=255)),
                ('agencyTimeZone', models.CharField(max_length=255)),
                ('agencyLang', models.CharField(max_length=255)),
                ('agencyPhone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CalenderModel',
            fields=[
                ('serviceID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('monday', models.CharField(max_length=255)),
                ('tuesday', models.CharField(max_length=255)),
                ('wednesday', models.CharField(max_length=255)),
                ('thursday', models.CharField(max_length=255)),
                ('friday', models.CharField(max_length=255)),
                ('saturday', models.CharField(max_length=255)),
                ('sunday', models.CharField(max_length=255)),
                ('startDate', models.CharField(max_length=255)),
                ('endDate', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EmailModel',
            fields=[
                ('email', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('firstName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=255)),
                ('end', models.CharField(max_length=255)),
                ('distance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RouteModel',
            fields=[
                ('routeID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('routeShortName', models.CharField(max_length=255)),
                ('routeLongName', models.CharField(max_length=255)),
                ('routeType', models.CharField(max_length=255)),
                ('agencyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.agencymodel')),
            ],
        ),
        migrations.CreateModel(
            name='ShapeModel',
            fields=[
                ('shapeID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('shapePtLat', models.CharField(max_length=255)),
                ('shapePtLon', models.CharField(max_length=255)),
                ('shapePtSequence', models.CharField(max_length=255)),
                ('shapeDistTravelled', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StopModel',
            fields=[
                ('stopID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('stopName', models.CharField(max_length=255)),
                ('stopLat', models.CharField(max_length=255)),
                ('stopLon', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TripModel',
            fields=[
                ('tripID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('tripHeadSign', models.CharField(max_length=255)),
                ('directionID', models.CharField(max_length=255)),
                ('routeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.routemodel')),
                ('serviceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.calendermodel')),
                ('shapeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.shapemodel')),
            ],
        ),
        migrations.CreateModel(
            name='TripTakenModel',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.emailmodel')),
                ('stopID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.stopmodel')),
                ('tripID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tripmodel')),
            ],
        ),
        migrations.CreateModel(
            name='TransfersModel',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('transferType', models.CharField(max_length=255)),
                ('minTransferTime', models.CharField(max_length=255)),
                ('fromStopID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from_stop', to='main.stopmodel')),
                ('toStopID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to_stop', to='main.stopmodel')),
            ],
        ),
        migrations.CreateModel(
            name='StopTimeModel',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('arrivalTime', models.CharField(max_length=255)),
                ('scheduledArrivalTime', models.CharField(max_length=255)),
                ('departureTime', models.CharField(max_length=255)),
                ('stopSequence', models.CharField(max_length=255)),
                ('stopHeadSign', models.CharField(max_length=255)),
                ('pickUpType', models.CharField(max_length=255)),
                ('dropOffType', models.CharField(max_length=255)),
                ('shapeDistTravelled', models.CharField(max_length=255)),
                ('stopID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.stopmodel')),
                ('tripID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tripmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarDatesModel',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=255)),
                ('exceptionType', models.CharField(max_length=255)),
                ('serviceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.calendermodel')),
            ],
        ),
    ]
